# The main title of the site which will be used in places like <title> tag and logo section.
title: Witty Lion's Blog

email: wittylioncompany@gmail.com

# Primary description of the site.
description: >- # this means to ignore newlines until next directive
  This blogpost contains articles related to the all
  production made by the Witty Lion company.

# Main contacts of the author of the site.
author: Witty Lion

# GitHub pages URL.
url: "https://wittylion.github.io"
github_username:  wittylion

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-sitemap

google_analytics: UA-133153148-1

disqus:
  shortname: wittylion-github-io
